;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(repeat
                               end-of-buffer
                               move-text-up
                               duplicate-line-or-region-below
                               sgml-slash
                               backward-kill-line
                               indent-for-tab-command
                               kmacro-start-macro-or-insert-counter
                               python-indent-dedent-line-backspace
                               kill-region
                               mouse-set-point
                               mouse-drag-region
                               minibuffer-complete-and-exit))

(setq mc/cmds-to-run-once '())

                               