;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        ido-find-file
        jedi:dot-complete
        repeat
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        coffee-dedent-line-backspace
        python-indent-dedent-line-backspace
        ))
